- name: Deploy HTML App
  hosts: servers
  become: yes

  tasks:

    - name: Install dependencies
      apt:
        name:
          - docker.io
          - git
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove old app directory
      file:
        path: /home/ubuntu/app
        state: absent

    - name: Clone app repo from GitHub
      git:
        repo: https://github.com/utkarshapatilU/devops-project.git
        dest: /home/ubuntu/app
        force: yes

    - name: Build Docker image
      shell: |
        cd /home/ubuntu/app
        docker build -t html-app .

    - name: Stop old container if exists
      shell: docker rm -f html-app || true

    - name: Run new container
      shell: |
        docker run -d -p 80:80 --name html-app html-app
